# Generated by Django 6.0.2 on 2026-04-17 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('tech', 'Technology'), ('life', 'Lifestyle'), ('health', 'Health & Wellness'), ('business', 'Business'), ('edu', 'Education'), ('travel', 'Travel'), ('food', 'Food & Cooking'), ('sports', 'Sports'), ('ent', 'Entertainment'), ('other', 'Other')], default='other', max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='magazine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magazines', to='magazine.category'),
        ),
    ]
