# Generated by Django 6.0.2 on 2026-04-17 15:21

import django.db.models.deletion
import magazine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_category_magazine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='category',
            field=models.ForeignKey(default=magazine.models.get_other_category, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='magazines', to='magazine.category'),
        ),
    ]
