# Generated by Django 6.0.2 on 2026-04-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_alter_magazine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='slug',
            field=models.SlugField(default='temp-slug', unique=True),
            preserve_default=False,
        ),
    ]
