# Generated by Django 6.0.2 on 2026-04-25 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0006_alter_magazine_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/magazine_images/'),
        ),
    ]
